src/procedures/models.py
from sqlalchemy.orm.collections import attribute_mapped_collection
from sqlalchemy.ext.associationproxy import association_proxy
from src import db
from src.projects.models import Projects


class Procedures(db.Model):

  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  project_id = db.Column(db.Integer, db.ForeignKey('projects.id'), nullable=False)
  name = db.Column(db.String)
  description = db.Column(db.String)
  parameters = db.relationship('Parameters', backref='procedures', cascade='all, delete, delete-orphan', lazy=True)
  schedules = db.relationship('Schedules', backref='procedures', cascade='all, delete, delete-orphan', lazy=True)
  experiments = db.relationship('Experiments', backref='procedures', cascade='all, delete, delete-orphan', lazy=True)

  attribute_values = db.relationship('ProceduresValue', cascade='all, delete, delete-orphan', 
    collection_class=attribute_mapped_collection('_attribute_name'))

  attributes = association_proxy('attribute_values', 'value', 
    creator=lambda k, v: Value(k,v))

  def __str__(self):
    return Projects.query.get(self.project_id).name + ": " + self.name

  def __repr__(self):
    return Projects.query.get(self.project_id).name + ": " + self.name

  def get_project(self):
    return Projects.query.get(self.project_id)

  def get_project_name(self):
    return Projects.query.get(self.project_id).name

  @classmethod
  def all(cls):
    return db.session.query(cls).all()


class ProceduresAttribute(db.Model):

  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  name = db.Column(db.String(100), nullable=False, unique=True)

  values = db.relationship('ProceduresValue', backref="procedures_attribute", cascade='all, delete, delete-orphan')
  
  @classmethod
  def get_or_create(cls, name, *arg, **kw):
    with db.session.no_autoflush:
      q = cls.query.filter_by(name=name)
      obj = q.first()
      if not obj:
        obj = cls(name, *arg, **kw)
        db.session.add(obj)
    return obj
    

class ProceduresValue(db.Model):
  __table_args__ = (
    db.UniqueConstraint('procedures_id', 'procedures_attribute_id'),
  )
  
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  procedures_id = db.Column(db.Integer, db.ForeignKey('procedures.id'), nullable=False)
  procedures_attribute_id = db.Column(db.Integer, db.ForeignKey('procedures_attribute.id'), nullable=False)
  value = db.Column(db.String)

  # Relationship to use in association proxy
  _attribute = db.relationship('ProceduresAttribute', uselist=False, 
    foreign_keys=[procedures_attribute_id], lazy='joined')

  # Expose attribute name as proxy
  _attribute_name = association_proxy('_attribute', 'name', 
    creator=lambda v: ProceduresAttribute.get_or_create(v))

  def __repr__(self):
    return self.value

  @classmethod
  def get_by_uniq_const(cls, procedure_id, attribute_id):
    return cls.query.filter_by(procedures_id=procedure_id, procedures_attribute_id=attribute_id).first()

src/procedures/forms.py
from wtforms import form, fields, validators
from src.projects.models import Projects
from wtforms_alchemy import QuerySelectField


class AddProcedures(form.Form):
	project_id = QuerySelectField('Project', query_factory=lambda: Projects.query)
	name = fields.StringField('Name', validators=[validators.required()])
	description = fields.TextAreaField('Description')


class EditProcedure(AddProcedures):
	id = fields.HiddenField()


class AddProceduresAttribute(form.Form):
	name = fields.StringField('Name', validators=[validators.required()])
	submit = fields.SubmitField('Submit')


class EditProceduresAttribute(AddProceduresAttribute):
	id = fields.HiddenField()

src/procedures/controllers.py
# Import flask dependencies
import os
from flask import (
    Blueprint, request, render_template,
    redirect, url_for)
from src import db
import src.procedures.models as ProcedureModels
import src.procedures.forms as ProcedureForms
from flask_admin import helpers
from src.helpers.decorators import check_login, check_admin


procedures = Blueprint('procedures', __name__, url_prefix='/procedures')


@procedures.route('/', methods=['GET'])
@check_login
def index():
    procedures = ProcedureModels.Procedures.query.all()
    attributes = ProcedureModels.ProceduresAttribute.query.all()
    return render_template("procedures/index.html", procedures=procedures, attributes=attributes)


@procedures.route('/<int:procedure_id>', methods=['GET'])
@check_login
def view(procedure_id):
    procedure = ProcedureModels.Procedures.query.get(procedure_id)
    return render_template("procedures/view.html", procedure=procedure)


@procedures.route('/add', methods=['GET', 'POST'])
@check_login
def add():
    attributes = ProcedureModels.ProceduresAttribute.query.all()
    form = ProcedureForms.AddProcedures(request.form)
    if request.method == 'POST':
        procedure = ProcedureModels.Procedures()
        procedure.project_id = request.form.get('project_id')
        procedure.name = request.form.get('name')
        procedure.description = request.form.get('description')
        db.session.add(procedure)
        db.session.flush()
        for attribute in attributes:
            procedure_attribute = ProcedureModels.ProceduresValue()
            procedure_attribute.procedures_id = procedure.id
            procedure_attribute.procedures_attribute_id = attribute.id
            procedure_attribute.value = request.form.get(attribute.name)
            db.session.add(procedure_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit.html", form=form, attributes=attributes)


@procedures.route('/edit/<int:procedure_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit(procedure_id):
    attributes = ProcedureModels.ProceduresAttribute.query.all()
    procedure = ProcedureModels.Procedures.query.get(procedure_id)
    form = ProcedureForms.EditProcedure(request.form, obj=procedure)
    if request.method == 'POST':
        procedure.start_datetime = request.form.get('start_datetime')
        procedure.end_datetime = request.form.get('end_datetime')
        procedure.procedure_id = request.form.get('procedure_id')
        for specimen in request.form.getlist('specimens'):
            procedure.specimens.append(Specimens.query.get(specimen))
        for user in request.form.getlist('users'):
            procedure.users.append(User.query.get(user))
        db.session.add(procedure)
        db.session.flush()
        for attribute in attributes:
            procedure_attribute = ProcedureModels.ProceduresValue.get_by_uniq_const(procedure_id, attribute.id)
            if not procedure_attribute:
                procedure_attribute = ProcedureModels.ProceduresValue()
            procedure_attribute.procedures_id = procedure.id
            procedure_attribute.procedures_attribute_id = attribute.id
            procedure_attribute.value = request.form.get(attribute.name)
            db.session.add(procedure_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit.html", form=form, attributes=attributes, edit=1, procedure=procedure)


@procedures.route('/delete/<int:procedure_id>', methods=['GET'])
@check_login
@check_admin
def delete(procedure_id):
    procedure = ProcedureModels.Procedures.query.get_or_404(procedure_id)
    db.session.delete(procedure)
    db.session.commit()
    return redirect(url_for('procedures.index'))


@procedures.route('/attribute_add', methods=['GET', 'POST'])
@check_login
def attribute_add():
    form = ProcedureForms.AddProceduresAttribute(request.form)
    if helpers.validate_form_on_submit(form):
        attribute = ProcedureModels.ProceduresAttribute()
        form.populate_obj(attribute)
        db.session.add(attribute)
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit_attribute.html", form=form)


@procedures.route('/attribute/edit/<int:procedure_attribute_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def attribute_edit(procedure_attribute_id):
    procedure_attribute = ProcedureModels.ProceduresAttribute.query.get(procedure_attribute_id)
    form = ProcedureForms.EditProceduresAttribute(request.form, obj=procedure_attribute)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(procedure_attribute)
        db.session.add(procedure_attribute)
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit_attribute.html", form=form, edit=1, procedure_attribute_id=procedure_attribute_id)


@procedures.route('/attribute/delete/<int:procedure_attribute_id>', methods=['GET'])
@check_login
@check_admin
def attribute_delete(procedure_attribute_id):
    procedure_attribute = ProcedureModels.ProceduresAttribute.query.get_or_404(procedure_attribute_id)
    db.session.delete(procedure_attribute)
    db.session.commit()
    return redirect(url_for('procedures.index'))

src/site/controllers.py
# Import flask dependencies
import os
from flask import (
    Blueprint, request, render_template,
    redirect, url_for, jsonify)
from src import db, app
import src.site.models as SiteModels
import src.site.forms as SiteForms
from src.schedules.models import Schedules
from flask_admin import helpers
from werkzeug.utils import secure_filename
from src.helpers.decorators import check_login, check_admin
from src.helpers.utils import slugify, get_iqr_range
from flask_login import current_user
from src.procedures.models import Procedures
from src.parameters.models import Parameters


site = Blueprint('site', __name__, url_prefix='')


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']


@site.route('/', methods=['GET'])
def index():
    return render_template("/site/welcome.html")


@site.route('/dashboard', methods=['GET'])
@check_login
def dashboard():
    data = {'projects': SiteModels.Projects.query.all(), 'schedules': Schedules().get_user_schedule(current_user.get_id())}
    return render_template("/site/dashboard.html", data=data)


@site.route('/experiments/', methods=['GET'])
@check_login
def experiments():
    experiments = SiteModels.Experiments.query.all()
    attributes = SiteModels.ExperimentsAttribute.query.all()
    if request.args.get('ajax'):
        data = []
        for experiment in experiments:
            data_set = [experiment.get_datetime().strftime('%m/%d/%Y %H:%M'),
                experiment.get_project().name,
                experiment.get_procedure().name,
                experiment.get_specimen().name]
            for attribute in attributes:
                data_set.append(experiment.attributes.get(attribute.name).value)
            data_set.append(render_template('/site/experiments/view_data.html', experiment_id=experiment.id))
            data.append(data_set)
        return jsonify({'data': data})
    return render_template("/site/experiments/index.html", experiments=experiments, attributes=attributes)


@site.route('/experiments/<int:experiment_id>', methods=['GET'])
@check_login
def experiments_view(experiment_id):
    experiment = SiteModels.Experiments.query.get(experiment_id)
    return render_template("/site/experiments/view.html", experiment=experiment)


@site.route('/data/collect/<int:schedule_id>/', methods=['GET', 'POST'])
@check_login
def collect_data(schedule_id):
    schedule = Schedules.query.get(schedule_id)
    if request.method == 'POST':
        for specimen in schedule.specimens:
            experiment = SiteModels.Experiments()
            experiment.schedule_id = schedule_id
            experiment.specimen_id = specimen.id
            experiment.project_id = schedule.get_project_id()
            experiment.procedure_id = schedule.procedure_id
            db.session.add(experiment)
            db.session.flush()
            for parameter in schedule.get_procedure().parameters:
                datapoint = SiteModels.DataPoints()
                data_type = parameter.get_datatype()
                
                if data_type == 'File':
                    classInstance = datapoint.get_class_by_string(data_type)
                    file = request.files.get('[' + parameter.name + '][' + str(specimen.id) + ']')
                    if file and allowed_file(file.filename):
                        slug = slugify(experiment.get_procedure().name) + "/"
                        if not os.path.exists(app.config['UPLOAD_FOLDER'] + slug):
                            os.makedirs(app.config['UPLOAD_FOLDER'] + slug)
                        filename = secure_filename(file.filename)
                        file.save(os.path.join(app.config['UPLOAD_FOLDER'] + slug, filename))
                        classInstance.value = slug + filename
                    else:
                        classInstance.value = None
                else:
                    data_value = request.form.get('[' + parameter.name + '][' + str(specimen.id) + ']')
                    classInstance = datapoint.get_by_value(data_type, data_value)
                    
                    if not classInstance:
                        classInstance = datapoint.get_class_by_string(data_type)

                        if data_type == 'Option':
                            classInstance.option_id = data_value
                        else:
                            classInstance.value = data_value

                        db.session.add(classInstance)
                        db.session.flush()
                    datapoint.experiment_id = experiment.id
                    datapoint.parameter_id = parameter.id
                    datapoint.data_point_id = classInstance.id
                    db.session.add(datapoint)
                    db.session.flush()
        db.session.commit()
        return redirect(url_for('schedules.view', schedule_id=schedule_id))
        
    return render_template("/site/collect_data.html", schedule=schedule)


@site.route('/data/<int:procedure_id>/', methods=['GET'])
@check_login
def procedure_data(procedure_id):
    experiments = SiteModels.Experiments.get_by_procedure(procedure_id)
    procedure = Procedures.query.get(procedure_id)
    if request.args.get('ajax'):
        data = []
        for experiment in experiments:
            data_set = [experiment.get_specimen().name]
            for data_point in experiment.data_points:
                data_set.append(str(data_point.get_value()))
            data.append(data_set)
        return jsonify({'data': data})
    return render_template("/site/procedure_data.html", experiments=experiments, procedure=procedure)


@site.route('/outliers/<int:parameter_id>/', methods=['GET'])
@check_login
def outliers(parameter_id):
    parameter = Parameters.query.get(parameter_id)
    data_points = []
    for point in parameter.data_points:
        data_points.append(float(point.get_value()))
    data = get_iqr_range(data_points)
    return render_template("/site/outliers.html", data=data, parameter=parameter)


@site.route('/charts', methods=['GET', 'POST'])
@check_login
def charts():
    form = SiteForms.ChartForm(request.form)
    if request.method == 'POST':
        parameter_a = form.data['parameter_id_a']
        parameter_b = form.data['parameter_id_b']
        data = {}
        for data_point in parameter_a.data_points:
            specimen_name = data_point.get_specimen_name()
            data[specimen_name] = []
            data[specimen_name].append(data_point.get_value())
        for data_point in parameter_b.data_points:
            specimen_name = data_point.get_specimen_name()
            data[specimen_name].append(data_point.get_value())
        return render_template("/site/charts.html", parameter_a=parameter_a, parameter_b=parameter_b, data=data, has_data=True,
            form=form)
    return render_template("/site/charts.html", has_data=False, form=form)

src/templates/procedures/add_or_edit.html
{% extends "base.html" %}
{% block title %}{% if edit %}Edit{% else %}Add{% endif %} Procedure{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
    <form action="{% if edit %} {{ url_for('procedures.edit', procedure_id=procedure.id) }} {% else %} {{ url_for('procedures.add') }} {% endif %}" method="POST" class="ui form">
      {% for f in form %}
             <div class="field">
                {% if f.name == 'id' %}
                  {{ f }}
                {% elif f.type in ['QuerySelectMultipleField', 'QuerySelectField', 'SelectField'] %}
                  {{ f.label }}
                  {{ f(class='ui fluid search dropdown') }}
                {% elif f.name == 'start_datetime' or f.name == 'end_datetime' %}
                  {{ f.label }}
                  {{ f(type='datetime-local') }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
            </div>
        {% endfor %}


        {% for attribute in attributes %}
            <div class="field">
                <label for='{{ attribute.name }}'>{{ attribute.name }}</label>
                <input id='{{ attribute.name }}' type="text" name="{{ attribute.name }}" value="{% if edit %}{{ procedure.attribute_values.get(attribute.name) }}{% endif %}">   
            </div>
        {% endfor %}
        <a class="ui red left floated button" href="{{ url_for('procedures.index') }}">Cancel</a>
        <button type='submit' class="ui blue right floated button">Submit</button>
    </form>
  </div>
</div>
{% endblock %}


{% block script %}
  {% if edit %}
  <script>
    $(document).ready(function(){

      $('#project_id').val('{{ procedure.project_id }}');
      $('#project_id').trigger('change');

    })
  </script>
  {% endif %}
{% endblock %}

src/templates/procedures/add_or_edit_attribute.html
{% extends "base.html" %}
{% block title %}{% if edit %}Edit{% else %}Add{% endif %} Procedure Attribute{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
      <h1>{% if edit %}Edit{% else %}Add{% endif %} Procedure Attribute
        {% if edit %}<a class="ui red right floated button" href="{{ url_for('procedures.attribute_delete', procedure_attribute_id=procedure_attribute_id) }}">Delete Attribute</a>{% endif %}
      </h1>
    <form action="{% if edit %}{{ url_for('procedures.attribute_edit', procedure_attribute_id=procedure_attribute_id) }}{% else %}{{ url_for('procedures.attribute_add') }}{% endif %}" method="POST" class="ui form">
        {% for f in form %}
             <div class="field">
                {% if f.name == 'submit' %}
                  <a class="ui red left floated button" href="{{ url_for('procedures.index') }}">Cancel</a>
                  {{ f(class='ui blue right floated button') }}
                {% elif f.name == 'id' %}
                  {{ f }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
              </div>
        {% endfor %}
    </form>
  </div>
</div>
{% endblock %}

src/templates/procedures/index.html
{% extends "base.html" %}
{% block title %}Procedures{% endblock %}

{% block content %}
<div class="ui one column grid container">
    <div class="column">
	    <h1>Procedures 	
	      	<a class="ui yellow right floated button" href="{{ url_for('procedures.attribute_add') }}">Add Attribute</a>
	      	<a class="ui green right floated button" href="{{ url_for('procedures.add') }}">Add Procedure</a>
	    </h1>
	    <table class="ui striped table">
      	<thead>
	      <tr>
	      	<th>Project</th>
	      	<th>Procedure</th>
	      	<th>Description</th>
	      	{% for attribute in attributes %}
	      		<th><a href='{{ url_for("procedures.attribute_edit", procedure_attribute_id=attribute.id) }}'>{{ attribute.name|uc_words }}</a></th>
	      	{% endfor %}
	      	<th>Data</th>
	      </tr>
	  </thead>
	  <tbody>
	      {% for procedure in procedures %}
	      <tr>
	      	<td>{{ procedure.get_project_name() }}</td>
	      	<td nowrap><a href="{{ url_for('procedures.view', procedure_id=procedure.id) }}">{{ procedure.name }}</a></td>
	      	<td>{{ procedure.description }}</td>
	      	{% for attribute in attributes %}
	      		<td>{{procedure.attributes.get(attribute.name)}}</td>
	      	{% endfor %}
	      	<td>
	      		<a class='ui blue vertical animated button' href="{{ url_for('site.procedure_data', procedure_id=procedure.id) }}">
      				<div class="hidden content">View</div>
	      			<div class="visible content">
	      				<i class="table icon" aria-hidden="true"></i>
	      			</div>
	      		</a>
	      	</td>
	      </tr>
	      {% endfor %}
	  </tbody>
	  </table>
    </div>
</div>
{% endblock %}

src/templates/procedures/view.html
{% extends "base.html" %}
{% block title %}{{ procedure.name }}{% endblock %}

{% block content %}
<div class="ui one column grid container">
    <div class="column">
	    <h1>{{ procedure.name }}
	      	<a class="ui green right floated button" href="{{ url_for('parameters.add') }}">Add Parameter</a>
	      	<a class="ui blue right floated button" href="{{ url_for('procedures.edit', procedure_id=procedure.id) }}">Edit Procedure</a>
	    </h1>
	    <p>{{ procedure.description }}</p>
	    
	    {% if procedure.attributes|length > 0 %}
		    <h3>Attributes</h3>
		    {% for attribute in procedure.attributes %}
		      <p>{{ attribute.name|uc_words }}: {{ procedure.attribute_values.get(attribute) }}</p>
		    {% endfor %}
	    {% endif %}

	    {% if procedure.parameters|length > 0 %}
		    <h3>Parameters</h3>
		    {% for parameter in procedure.parameters %}
		    	<p>{{ parameter.name|uc_words }}</p>
		    {% endfor %}
		{% else %}
			<h2>This Procedure Has No Parameters</h2>
		{% endif %}


    </div>
</div>
{% endblock %}