src/projects/models.py
from sqlalchemy.orm.collections import attribute_mapped_collection
from sqlalchemy.ext.associationproxy import association_proxy
from src import db


class Projects(db.Model):

  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  procedures = db.relationship('Procedures', backref='projects', cascade='all, delete, delete-orphan', lazy=True)
  name = db.Column(db.String)
  description = db.Column(db.String)
  experiments = db.relationship('Experiments', backref='projects', cascade='all, delete, delete-orphan', lazy=True)

  attribute_values = db.relationship('ProjectsValue', cascade='all, delete, delete-orphan', 
    collection_class=attribute_mapped_collection('_attribute_name'))

  attributes = association_proxy('attribute_values', 'value', 
    creator=lambda k, v: Value(k,v))

  def __repr__(self):
    return self.name

  @classmethod
  def all(cls):
    return db.session.query(cls).all()


class ProjectsAttribute(db.Model):

  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  name = db.Column(db.String(100), nullable=False, unique=True)

  values = db.relationship('ProjectsValue', backref="projects_attribute", cascade='all, delete, delete-orphan')

  @classmethod
  def get_or_create(cls, name, *arg, **kw):
    with db.session.no_autoflush:
      q = cls.query.filter_by(name=name)
      obj = q.first()
      if not obj:
        obj = cls(name, *arg, **kw)
        db.session.add(obj)
    return obj


class ProjectsValue(db.Model):
  __table_args__ = (
    db.UniqueConstraint('projects_id', 'projects_attribute_id'),
  )

  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  projects_id = db.Column(db.Integer, db.ForeignKey('projects.id'), nullable=False)
  projects_attribute_id = db.Column(db.Integer, db.ForeignKey('projects_attribute.id'), nullable=False)
  value = db.Column(db.String)

  # Relationship to use in association proxy
  _attribute = db.relationship('ProjectsAttribute', uselist=False, 
    foreign_keys=[projects_attribute_id], lazy='joined')

  # Expose attribute name as proxy
  _attribute_name = association_proxy('_attribute', 'name', 
    creator=lambda v: ProjectsAttribute.get_or_create(v))

  def __repr__(self):
    return self.value

  @classmethod
  def get_by_project_id_name(cls, project_id, name):
    attribute = ProjectsAttribute.query.filter_by(name=name)
    return cls.query.filter_by(projects_id=project_id, projects_attribute_id=attribute.id).first()

  @classmethod
  def get_by_uniq_const(cls, project_id, attribute_id):
    return cls.query.filter_by(projects_id=project_id, projects_attribute_id=attribute_id).first()

src/projects/forms.py
from wtforms import form, fields, validators


class AddProjects(form.Form):
	name = fields.StringField('Name', validators=[validators.required()])
	description = fields.TextAreaField('Description')


class EditProjectsForm(AddProjects):
	id = fields.HiddenField()


class AddProjectsAttribute(form.Form):
	name = fields.StringField('Name', validators=[validators.required()])
	submit = fields.SubmitField('Submit')


class EditProjectsAttribute(AddProjectsAttribute):
	id = fields.HiddenField()

src/procedures/controllers.py
# Import flask dependencies
import os
from flask import (
    Blueprint, request, render_template,
    redirect, url_for)
from src import db
import src.procedures.models as ProcedureModels
import src.procedures.forms as ProcedureForms
from flask_admin import helpers
from src.helpers.decorators import check_login, check_admin


procedures = Blueprint('procedures', __name__, url_prefix='/procedures')


@procedures.route('/', methods=['GET'])
@check_login
def index():
    procedures = ProcedureModels.Procedures.query.all()
    attributes = ProcedureModels.ProceduresAttribute.query.all()
    return render_template("procedures/index.html", procedures=procedures, attributes=attributes)


@procedures.route('/<int:procedure_id>', methods=['GET'])
@check_login
def view(procedure_id):
    procedure = ProcedureModels.Procedures.query.get(procedure_id)
    return render_template("procedures/view.html", procedure=procedure)


@procedures.route('/add', methods=['GET', 'POST'])
@check_login
def add():
    attributes = ProcedureModels.ProceduresAttribute.query.all()
    form = ProcedureForms.AddProcedures(request.form)
    if request.method == 'POST':
        procedure = ProcedureModels.Procedures()
        procedure.project_id = request.form.get('project_id')
        procedure.name = request.form.get('name')
        procedure.description = request.form.get('description')
        db.session.add(procedure)
        db.session.flush()
        for attribute in attributes:
            procedure_attribute = ProcedureModels.ProceduresValue()
            procedure_attribute.procedures_id = procedure.id
            procedure_attribute.procedures_attribute_id = attribute.id
            procedure_attribute.value = request.form.get(attribute.name)
            db.session.add(procedure_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit.html", form=form, attributes=attributes)


@procedures.route('/edit/<int:procedure_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit(procedure_id):
    attributes = ProcedureModels.ProceduresAttribute.query.all()
    procedure = ProcedureModels.Procedures.query.get(procedure_id)
    form = ProcedureForms.EditProcedure(request.form, obj=procedure)
    if request.method == 'POST':
        procedure.start_datetime = request.form.get('start_datetime')
        procedure.end_datetime = request.form.get('end_datetime')
        procedure.procedure_id = request.form.get('procedure_id')
        for specimen in request.form.getlist('specimens'):
            procedure.specimens.append(Specimens.query.get(specimen))
        for user in request.form.getlist('users'):
            procedure.users.append(User.query.get(user))
        db.session.add(procedure)
        db.session.flush()
        for attribute in attributes:
            procedure_attribute = ProcedureModels.ProceduresValue.get_by_uniq_const(procedure_id, attribute.id)
            if not procedure_attribute:
                procedure_attribute = ProcedureModels.ProceduresValue()
            procedure_attribute.procedures_id = procedure.id
            procedure_attribute.procedures_attribute_id = attribute.id
            procedure_attribute.value = request.form.get(attribute.name)
            db.session.add(procedure_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit.html", form=form, attributes=attributes, edit=1, procedure=procedure)


@procedures.route('/delete/<int:procedure_id>', methods=['GET'])
@check_login
@check_admin
def delete(procedure_id):
    procedure = ProcedureModels.Procedures.query.get_or_404(procedure_id)
    db.session.delete(procedure)
    db.session.commit()
    return redirect(url_for('procedures.index'))


@procedures.route('/attribute_add', methods=['GET', 'POST'])
@check_login
def attribute_add():
    form = ProcedureForms.AddProceduresAttribute(request.form)
    if helpers.validate_form_on_submit(form):
        attribute = ProcedureModels.ProceduresAttribute()
        form.populate_obj(attribute)
        db.session.add(attribute)
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit_attribute.html", form=form)


@procedures.route('/attribute/edit/<int:procedure_attribute_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def attribute_edit(procedure_attribute_id):
    procedure_attribute = ProcedureModels.ProceduresAttribute.query.get(procedure_attribute_id)
    form = ProcedureForms.EditProceduresAttribute(request.form, obj=procedure_attribute)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(procedure_attribute)
        db.session.add(procedure_attribute)
        db.session.commit()
        return redirect(url_for('procedures.index'))

    return render_template("procedures/add_or_edit_attribute.html", form=form, edit=1, procedure_attribute_id=procedure_attribute_id)


@procedures.route('/attribute/delete/<int:procedure_attribute_id>', methods=['GET'])
@check_login
@check_admin
def attribute_delete(procedure_attribute_id):
    procedure_attribute = ProcedureModels.ProceduresAttribute.query.get_or_404(procedure_attribute_id)
    db.session.delete(procedure_attribute)
    db.session.commit()
    return redirect(url_for('procedures.index'))

src/projects/controllers.py
# Import flask dependencies
from flask import (
    Blueprint, request, render_template,
    redirect, url_for)
from src import db
import src.projects.models as ProjectsModels
import src.projects.forms as ProjectsForms
from flask_admin import helpers
from src.helpers.decorators import check_login, check_admin

projects = Blueprint('projects', __name__, url_prefix='/projects')


@projects.route('/', methods=['GET'])
@check_login
def index():
    projects = ProjectsModels.Projects.query.all()
    attributes = ProjectsModels.ProjectsAttribute.query.all()
    return render_template("/projects/index.html", projects=projects, attributes=attributes)


@projects.route('/<int:project_id>', methods=['GET'])
@check_login
def view(project_id):
    project = ProjectsModels.Projects.query.get(project_id)
    return render_template("/projects/view.html", project=project)


@projects.route('/add', methods=['GET', 'POST'])
@check_login
def add():
    attributes = ProjectsModels.ProjectsAttribute.query.all()
    form = ProjectsForms.AddProjects(request.form)
    if request.method == 'POST':
        project = ProjectsModels.Projects()
        form.populate_obj(project)
        db.session.add(project)
        db.session.flush()
        for attribute in attributes:
            project_attribute = ProjectsModels.ProjectsValue()
            project_attribute.projects_id = project.id
            project_attribute.projects_attribute_id = attribute.id
            project_attribute.value = request.form.get(attribute.name)
            db.session.add(project_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('projects.index'))

    return render_template("projects/add_or_edit.html", form=form, attributes=attributes)


@projects.route('/edit/<int:project_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit(project_id):
    attributes = ProjectsModels.ProjectsAttribute.query.all()
    project = ProjectsModels.Projects.query.get(project_id)
    form = ProjectsForms.EditProjectsForm(request.form, obj=project)
    if request.method == 'POST':
        form.populate_obj(project)
        db.session.add(project)
        db.session.flush()
        for attribute in attributes:
            project_attribute = ProjectsModels.ProjectsValue.get_by_uniq_const(project_id, attribute.id)
            if not project_attribute:
                project_attribute = ProjectsModels.ProjectsValue()
            project_attribute.projects_id = project.id
            project_attribute.projects_attribute_id = attribute.id
            project_attribute.value = request.form.get(attribute.name)
            db.session.add(project_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('projects.index'))

    return render_template("projects/add_or_edit.html", form=form, attributes=attributes, edit=1, project=project)


@projects.route('/delete/<int:project_id>', methods=['GET'])
@check_login
@check_admin
def delete(project_id):
    project = ProjectsModels.Projects.query.get_or_404(project_id)
    db.session.delete(project)
    db.session.commit()
    return redirect(url_for('projects.index'))


@projects.route('/attribute/add', methods=['GET', 'POST'])
@check_login
def attribute_add():
    form = ProjectsForms.AddProjectsAttribute(request.form)
    if helpers.validate_form_on_submit(form):
        attribute = ProjectsModels.ProjectsAttribute()
        form.populate_obj(attribute)
        db.session.add(attribute)
        db.session.commit()
        return redirect(url_for('projects.index'))

    return render_template("projects/add_or_edit_attribute.html", form=form)


@projects.route('/attribute/edit/<int:project_attribute_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def attribute_edit(project_attribute_id):
    project_attribute = ProjectsModels.ProjectsAttribute.query.get(project_attribute_id)
    form = ProjectsForms.EditProjectsAttribute(request.form, obj=project_attribute)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(project_attribute)
        db.session.add(project_attribute)
        db.session.commit()
        return redirect(url_for('projects.index'))

    return render_template("projects/add_or_edit_attribute.html", form=form, edit=1, project_attribute_id=project_attribute_id)


@projects.route('/attribute/delete/<int:project_attribute_id>', methods=['GET'])
@check_login
@check_admin
def attribute_delete(project_attribute_id):
    project_attribute = ProjectsModels.ProjectsAttribute.query.get_or_404(project_attribute_id)
    db.session.delete(project_attribute)
    db.session.commit()
    return redirect(url_for('projects.index'))

src/templates/projects/add_or_edit.html
{% extends "base.html" %}
{% block title %}{% if edit %}Edit{% else %}Add{% endif %} Project{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
    <form action="{% if edit %} {{ url_for('projects.edit', project_id=project.id) }} {% else %} {{ url_for('projects.add') }} {% endif %}" method="POST" class="ui form">
      {% for f in form %}
             <div class="field">
                {% if f.name == 'id' %}
                  {{ f }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
            </div>
        {% endfor %}


        {% for attribute in attributes %}
            <div class="field">
                <label for='{{ attribute.name }}'>{{ attribute.name }}</label>
                <input id='{{ attribute.name }}' type="text" name="{{ attribute.name }}" value="{% if edit %}{{ project.attribute_values.get(attribute.name) }}{% endif %}">		
            </div>
        {% endfor %}
        <a class="ui red left floated button" href="{{ url_for('projects.index') }}">Cancel</a>
        <button type='submit' class="ui blue right floated button">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

src/templates/projects/add_or_edit_attribute.html
{% extends "base.html" %}
{% block title %}{% if edit %}Edit{% else %}Add{% endif %} Project Attribute{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
      <h1>{% if edit %}Edit{% else %}Add{% endif %} Project Attribute
        {% if edit %}<a class="ui red right floated button" href="{{ url_for('projects.attribute_delete', project_attribute_id=project_attribute_id) }}">Delete Attribute</a>{% endif %}
      </h1>
    <form action="{% if edit %}{{ url_for('projects.attribute_edit', project_attribute_id=project_attribute_id) }}{% else %}{{ url_for('projects.attribute_add') }}{% endif %}" method="POST" class="ui form">
        {% for f in form %}
             <div class="field">
            		{% if f.name == 'submit' %}
                  <a class="ui red left floated button" href="{{ url_for('projects.index') }}">Cancel</a>
            			{{ f(class='ui blue right floated button') }}
                {% elif f.name == 'id' %}
                  {{ f }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
              </div>
        {% endfor %}
    </form>
  </div>
</div>
{% endblock %}

src/templates/projects/index.html
{% extends "base.html" %}
{% block title %}Projects{% endblock %}

{% block content %}
<div class="ui one column grid container">
    <div class="column">
	    <h1>Projects 	
	      	<a class="ui yellow right floated button" href="{{ url_for('projects.attribute_add') }}">Add Attribute</a>
	      	<a class="ui green right floated button" href="{{ url_for('projects.add') }}">Add Project</a>
	    </h1>
	    <table class="ui striped table">
      	<thead>
	      <tr>
	      	<th>Project</th>
	      	<th>Description</th>
	      	{% for attribute in attributes %}
	      		<th><a href='{{ url_for("projects.attribute_edit", project_attribute_id=attribute.id) }}'>{{ attribute.name|uc_words }}</a></th>
	      	{% endfor %}
	      </tr>
	  </thead>
	  <tbody>
	      {% for project in projects %}
	      <tr>
	      	<td nowrap><a href="{{ url_for('projects.view', project_id=project.id) }}">{{ project.name }}</a></td>
	      	<td>{{ project.description }}</td>
	      	{% for attribute in attributes %}
	      		<td>{{project.attributes.get(attribute.name)}}</td>
	      	{% endfor %}
	      </tr>
	      {% endfor %}
	  </tbody>
	  </table>
    </div>
</div>
{% endblock %}

src/templates/projects/view.html
{% extends "base.html" %}
{% block title %}{{ project.name }}{% endblock %}

{% block content %}
<div class="ui one column grid container">
    <div class="column">
	    <h1>{{ project.name }}
	      	<a class="ui green right floated button" href="{{ url_for('procedures.add') }}">Add Procedure</a>
	      	<a class="ui blue right floated button" href="{{ url_for('projects.edit', project_id=project.id) }}">Edit Project</a>
	      	<a class="ui red right floated button" href="{{ url_for('projects.delete', project_id=project.id) }}">Delete Project</a>
	    </h1>
	    <p>{{ project.description }}</p>
	    {% for attribute in project.attributes %}
	    	<p>{{ attribute.name|uc_words }}: {{ project.attribute_values.get(attribute) }}</p>
	    {% endfor %}
    </div>
</div>
{% endblock %}