src/schedules/forms.py
from wtforms import form, fields, validators
import src.schedules.models as SchedulesModels
from wtforms_alchemy import QuerySelectMultipleField, QuerySelectField
from src.auth.models import User
from src.specimens.models import Specimens


def specimens():
    return Specimens.all()

def users():
    return User.all()


class AddSchedule(form.Form):
	start_datetime = fields.StringField('Start DateTime', validators=[validators.required()])
	end_datetime = fields.StringField('End DateTime', validators=[validators.required()])
	specimens = QuerySelectMultipleField('Specimens', query_factory=specimens, allow_blank=False)
	users = QuerySelectMultipleField('Assigned To', query_factory=users, allow_blank=False)
	procedure_id = QuerySelectField('Procedure', query_factory=lambda: SchedulesModels.Procedures.query)
	

class EditSchedule(AddSchedule):
	id = fields.HiddenField()


class AddSchedulesAttribute(form.Form):
	name = fields.StringField('Name', validators=[validators.required()])
	submit = fields.SubmitField('Submit')

class EditSchedulesAttribute(AddSchedulesAttribute):
	id = fields.HiddenField()

src/schedules/controllers.py
# Import flask dependencies
import os
from flask import (
    Blueprint, request, render_template,
    redirect, url_for)
from src import db
import src.schedules.models as SchedulesModels
import src.schedules.forms as SchedulesForms
from flask_admin import helpers
from src.helpers.decorators import check_login, check_admin
from src.auth.models import User
from src.specimens.models import Specimens



schedules = Blueprint('schedules', __name__, url_prefix='/schedules')


@schedules.route('/', methods=['GET'])
@check_login
def index():
    schedules = SchedulesModels.Schedules.query.all()
    attributes = SchedulesModels.SchedulesAttribute.query.all()
    return render_template("/schedules/index.html", schedules=schedules, attributes=attributes)


@schedules.route('/calendar', methods=['GET'])
@check_login
def calendar():
    schedules = SchedulesModels.Schedules.query.all()
    return render_template("/schedules/calendar.html", schedules=schedules)



@schedules.route('/view/<int:schedule_id>', methods=['GET'])
@check_login
def view(schedule_id):
    schedule = SchedulesModels.Schedules.query.get(schedule_id)
    return render_template("/schedules/view.html", schedule=schedule)


@schedules.route('/update/', methods=['POST'])
@check_login
def update():
    if request.method == 'POST':
        schedule_data = request.get_json()
        print(schedule_data)
        schedule = SchedulesModels.Schedules.query.get(schedule_data['schedule_id'])
        if schedule:
            schedule.start_datetime = schedule.set_datetime(schedule_data['start_datetime'])
            schedule.end_datetime = schedule.set_datetime(schedule_data['end_datetime'])
            db.session.add(schedule)
            db.session.commit()
            return 'ok'
        return 'failed'
    return redirect(url_for('schedules.index'))


@schedules.route('/add', methods=['GET', 'POST'])
@check_login
def add():
    attributes = SchedulesModels.SchedulesAttribute.query.all()
    form = SchedulesForms.AddSchedule(request.form)
    if request.method == 'POST':
        schedule = SchedulesModels.Schedules()
        schedule.start_datetime = request.form.get('start_datetime')
        schedule.end_datetime = request.form.get('end_datetime')
        schedule.procedure_id = request.form.get('procedure_id')
        for specimen in request.form.getlist('specimens'):
            schedule.specimens.append(Specimens.query.get(specimen))
        for user in request.form.getlist('users'):
            schedule.users.append(User.query.get(user))
        db.session.add(schedule)
        db.session.flush()
        for attribute in attributes:
            schedule_attribute = SchedulesModels.SchedulesValue()
            schedule_attribute.schedules_id = schedule.id
            schedule_attribute.schedules_attribute_id = attribute.id
            schedule_attribute.value = request.form.get(attribute.name)
            db.session.add(schedule_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('schedules.index'))

    return render_template("schedules/add_or_edit.html", form=form, attributes=attributes)


@schedules.route('/edit/<int:schedule_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit(schedule_id):
    attributes = SchedulesModels.SchedulesAttribute.query.all()
    schedule = SchedulesModels.Schedules.query.get(schedule_id)
    form = SchedulesForms.EditSchedule(request.form, obj=schedule)
    if request.method == 'POST':
        schedule.start_datetime = request.form.get('start_datetime')
        schedule.end_datetime = request.form.get('end_datetime')
        schedule.procedure_id = request.form.get('procedure_id')
        for specimen in request.form.getlist('specimens'):
            schedule.specimens.append(Specimens.query.get(specimen))
        for user in request.form.getlist('users'):
            schedule.users.append(User.query.get(user))
        db.session.add(schedule)
        db.session.flush()
        for attribute in attributes:
            schedule_attribute = SchedulesModels.SchedulesValue.get_by_uniq_const(schedule_id, attribute.id)
            if not schedule_attribute:
                schedule_attribute = SchedulesModels.SchedulesValue()
            schedule_attribute.schedules_id = schedule.id
            schedule_attribute.schedules_attribute_id = attribute.id
            schedule_attribute.value = request.form.get(attribute.name)
            db.session.add(schedule_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('schedules.index'))

    return render_template("schedules/add_or_edit.html", form=form, attributes=attributes, edit=1, schedule=schedule)


@schedules.route('/delete/<int:schedule_id>', methods=['GET'])
@check_login
@check_admin
def delete(schedule_id):
    schedule = SchedulesModels.Schedules.query.get_or_404(schedule_id)
    db.session.delete(schedule)
    db.session.commit()
    return redirect(url_for('schedules.index'))


@schedules.route('/attribute/add', methods=['GET', 'POST'])
@check_login
def attribute_add():
    form = SchedulesForms.AddSchedulesAttribute(request.form)
    if helpers.validate_form_on_submit(form):
        attribute = SchedulesModels.SchedulesAttribute()
        form.populate_obj(attribute)
        db.session.add(attribute)
        db.session.commit()
        return redirect(url_for('schedules.index'))

    return render_template("schedules/add_or_edit_attribute.html", form=form)


@schedules.route('/attribute/edit/<int:schedule_attribute_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def attribute_edit(schedule_attribute_id):
    schedule_attribute = SchedulesModels.SchedulesAttribute.query.get(schedule_attribute_id)
    form = SchedulesForms.EditSchedulesAttribute(request.form, obj=schedule_attribute)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(schedule_attribute)
        db.session.add(schedule_attribute)
        db.session.commit()
        return redirect(url_for('schedules.index'))

    return render_template("schedules/add_or_edit_attribute.html", form=form, edit=1, schedule_attribute_id=schedule_attribute_id)


@schedules.route('/attribute/delete/<int:schedule_attribute_id>', methods=['GET'])
@check_login
@check_admin
def attribute_delete(schedule_attribute_id):
    schedule_attribute = SchedulesModels.SchedulesAttribute.query.get_or_404(schedule_attribute_id)
    db.session.delete(schedule_attribute)
    db.session.commit()
    return redirect(url_for('schedules.index'))

src/site/controllers.py
# Import flask dependencies
import os
from flask import (
    Blueprint, request, render_template,
    redirect, url_for, jsonify)
from src import db, app
import src.site.models as SiteModels
import src.site.forms as SiteForms
from src.schedules.models import Schedules
from flask_admin import helpers
from werkzeug.utils import secure_filename
from src.helpers.decorators import check_login, check_admin
from src.helpers.utils import slugify, get_iqr_range
from flask_login import current_user
from src.procedures.models import Procedures
from src.parameters.models import Parameters


site = Blueprint('site', __name__, url_prefix='')


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']


@site.route('/', methods=['GET'])
def index():
    return render_template("/site/welcome.html")


@site.route('/dashboard', methods=['GET'])
@check_login
def dashboard():
    data = {'projects': SiteModels.Projects.query.all(), 'schedules': Schedules().get_user_schedule(current_user.get_id())}
    return render_template("/site/dashboard.html", data=data)


@site.route('/experiments/', methods=['GET'])
@check_login
def experiments():
    experiments = SiteModels.Experiments.query.all()
    attributes = SiteModels.ExperimentsAttribute.query.all()
    if request.args.get('ajax'):
        data = []
        for experiment in experiments:
            data_set = [experiment.get_datetime().strftime('%m/%d/%Y %H:%M'),
                experiment.get_project().name,
                experiment.get_procedure().name,
                experiment.get_specimen().name]
            for attribute in attributes:
                data_set.append(experiment.attributes.get(attribute.name).value)
            data_set.append(render_template('/site/experiments/view_data.html', experiment_id=experiment.id))
            data.append(data_set)
        return jsonify({'data': data})
    return render_template("/site/experiments/index.html", experiments=experiments, attributes=attributes)


@site.route('/experiments/<int:experiment_id>', methods=['GET'])
@check_login
def experiments_view(experiment_id):
    experiment = SiteModels.Experiments.query.get(experiment_id)
    return render_template("/site/experiments/view.html", experiment=experiment)


@site.route('/data/collect/<int:schedule_id>/', methods=['GET', 'POST'])
@check_login
def collect_data(schedule_id):
    schedule = Schedules.query.get(schedule_id)
    if request.method == 'POST':
        for specimen in schedule.specimens:
            experiment = SiteModels.Experiments()
            experiment.schedule_id = schedule_id
            experiment.specimen_id = specimen.id
            experiment.project_id = schedule.get_project_id()
            experiment.procedure_id = schedule.procedure_id
            db.session.add(experiment)
            db.session.flush()
            for parameter in schedule.get_procedure().parameters:
                datapoint = SiteModels.DataPoints()
                data_type = parameter.get_datatype()
                
                if data_type == 'File':
                    classInstance = datapoint.get_class_by_string(data_type)
                    file = request.files.get('[' + parameter.name + '][' + str(specimen.id) + ']')
                    if file and allowed_file(file.filename):
                        slug = slugify(experiment.get_procedure().name) + "/"
                        if not os.path.exists(app.config['UPLOAD_FOLDER'] + slug):
                            os.makedirs(app.config['UPLOAD_FOLDER'] + slug)
                        filename = secure_filename(file.filename)
                        file.save(os.path.join(app.config['UPLOAD_FOLDER'] + slug, filename))
                        classInstance.value = slug + filename
                    else:
                        classInstance.value = None
                else:
                    data_value = request.form.get('[' + parameter.name + '][' + str(specimen.id) + ']')
                    classInstance = datapoint.get_by_value(data_type, data_value)
                    
                    if not classInstance:
                        classInstance = datapoint.get_class_by_string(data_type)

                        if data_type == 'Option':
                            classInstance.option_id = data_value
                        else:
                            classInstance.value = data_value

                        db.session.add(classInstance)
                        db.session.flush()
                    datapoint.experiment_id = experiment.id
                    datapoint.parameter_id = parameter.id
                    datapoint.data_point_id = classInstance.id
                    db.session.add(datapoint)
                    db.session.flush()
        db.session.commit()
        return redirect(url_for('schedules.view', schedule_id=schedule_id))
        
    return render_template("/site/collect_data.html", schedule=schedule)


@site.route('/data/<int:procedure_id>/', methods=['GET'])
@check_login
def procedure_data(procedure_id):
    experiments = SiteModels.Experiments.get_by_procedure(procedure_id)
    procedure = Procedures.query.get(procedure_id)
    if request.args.get('ajax'):
        data = []
        for experiment in experiments:
            data_set = [experiment.get_specimen().name]
            for data_point in experiment.data_points:
                data_set.append(str(data_point.get_value()))
            data.append(data_set)
        return jsonify({'data': data})
    return render_template("/site/procedure_data.html", experiments=experiments, procedure=procedure)


@site.route('/outliers/<int:parameter_id>/', methods=['GET'])
@check_login
def outliers(parameter_id):
    parameter = Parameters.query.get(parameter_id)
    data_points = []
    for point in parameter.data_points:
        data_points.append(float(point.get_value()))
    data = get_iqr_range(data_points)
    return render_template("/site/outliers.html", data=data, parameter=parameter)


@site.route('/charts', methods=['GET', 'POST'])
@check_login
def charts():
    form = SiteForms.ChartForm(request.form)
    if request.method == 'POST':
        parameter_a = form.data['parameter_id_a']
        parameter_b = form.data['parameter_id_b']
        data = {}
        for data_point in parameter_a.data_points:
            specimen_name = data_point.get_specimen_name()
            data[specimen_name] = []
            data[specimen_name].append(data_point.get_value())
        for data_point in parameter_b.data_points:
            specimen_name = data_point.get_specimen_name()
            data[specimen_name].append(data_point.get_value())
        return render_template("/site/charts.html", parameter_a=parameter_a, parameter_b=parameter_b, data=data, has_data=True,
            form=form)
    return render_template("/site/charts.html", has_data=False, form=form)

src/templates/schedules/add_or_edit.html
{% extends "base.html" %}
{% block title %}{% if edit %}Edit{% else %}Add{% endif %} Schedule{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
    <form action="{% if edit %} {{ url_for('schedules.edit', schedule_id=schedule.id) }} {% else %} {{ url_for('schedules.add') }} {% endif %}" method="POST" class="ui form">
      {% for f in form %}
             <div class="field">
                {% if f.name == 'id' %}
                  {{ f }}
                {% elif f.type in ['QuerySelectMultipleField', 'QuerySelectField', 'SelectField'] %}
                  {{ f.label }}
                  {{ f(class='ui fluid search dropdown') }}
                {% elif f.name == 'start_datetime' or f.name == 'end_datetime' %}
                  {{ f.label }}
                  {{ f(type='datetime-local') }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
            </div>
        {% endfor %}


        {% for attribute in attributes %}
            <div class="field">
                <label for='{{ attribute.name }}'>{{ attribute.name }}</label>
                <input id='{{ attribute.name }}' type="text" name="{{ attribute.name }}" value="{% if edit %}{{ schedule.attribute_values.get(attribute.name) }}{% endif %}">   
            </div>
        {% endfor %}
        <a class="ui red left floated button" href="{{ url_for('schedules.index') }}">Cancel</a>
        <button type='submit' class="ui blue right floated button">Submit</button>
    </form>
  </div>
</div>
{% endblock %}


{% block script %}
  {% if edit %}
  <script>
    $(document).ready(function(){
      {% if schedule.specimens|length > 0 %}
        var specimens = [];
        {% for specimen in schedule.specimens %}
          specimens.push('{{ specimen.id }}');
        {% endfor %}
        $('#specimens').val(specimens);
        $('#specimens').trigger('change');
      {% endif %}

      {% if schedule.users|length > 0 %}
        var users = [];
        {% for user in schedule.users %}
          users.push('{{ user.id }}');
        {% endfor %}
        $('#users').val(users);
        $('#users').trigger('change');
      {% endif %}

      $('#procedure_id').val('{{ schedule.procedure_id }}');
      $('#procedure_id').trigger('change');

    })
  </script>
  {% endif %}
{% endblock %}

src/templates/schedules/add_or_edit_attribute.html
{% extends "base.html" %}
{% block title %}{% if edit %}Edit{% else %}Add{% endif %} Schedule Attribute{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
      <h1>{% if edit %}Edit{% else %}Add{% endif %} Schedule Attribute
        {% if edit %}<a class="ui red right floated button" href="{{ url_for('schedules.attribute_delete', schedule_attribute_id=schedule_attribute_id) }}">Delete Attribute</a>{% endif %}
      </h1>
    <form action="{% if edit %}{{ url_for('schedules.attribute_edit', schedule_attribute_id=schedule_attribute_id) }}{% else %}{{ url_for('schedules.attribute_add') }}{% endif %}" method="POST" class="ui form">
        {% for f in form %}
             <div class="field">
                {% if f.name == 'submit' %}
                  <a class="ui red left floated button" href="{{ url_for('schedules.index') }}">Cancel</a>
                  {{ f(class='ui blue right floated button') }}
                {% elif f.name == 'id' %}
                  {{ f }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
              </div>
        {% endfor %}
    </form>
  </div>
</div>
{% endblock %}

src/templates/schedules/calendar.html
{% extends "base.html" %}
{% block title %}Schedule{% endblock %}

{% block style %}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.7.2/main.min.css">
{% endblock %}

{% block content %}

<div class="ui grid container">
  	<a class="ui green left floated button" href="{{ url_for('schedules.add') }}">Add Schedule</a>
	<a class="ui yellow right floated button" href="{{ url_for('schedules.attribute_add') }}">Add Attribute</a>
	<div id='calendar' style="width: 100%;"></div>
</div>

{% endblock %}

{% block script %}
	<script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.7.2/main.min.js"></script>
	<script>

      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'timeGridWeek',
          height: "auto",
          editable: true,
          slotMinTime: '06:00:00',
          slotMaxTime: '20:00:00',
          eventResize: function(info) {

		    if (!confirm(info.event.title + " end is now " + info.event.end.toISOString() + " is this okay?")) {
		      info.revert();
		    } else {
		    	$.ajax({
				  type: "POST",
				  url: '{{ url_for("schedules.update") }}',
				  data: JSON.stringify({'schedule_id': info.event.extendedProps.schedule_id, 'start_datetime': info.event.startStr, 'end_datetime': info.event.endStr}),
				  success: function(msg){
				  	console.log(msg);
				  },
				  contentType: "application/json",
        		  dataType: "json",
				});
		    }
		  },
		  eventDrop: function(info) {

		    if (!confirm(info.event.title + " was dropped on " + info.event.start.toISOString() + " Are you sure about this change?")) {
		      info.revert();
		    } else {
		    	$.ajax({
				  type: "POST",
				  url: '{{ url_for("schedules.update") }}',
				  data: JSON.stringify({'schedule_id': info.event.extendedProps.schedule_id, 'start_datetime': info.event.startStr, 'end_datetime': info.event.endStr}),
				  success: function(msg){
				  	console.log(msg);
				  },
				  contentType: "application/json",
        		  dataType: "json",
				});
		    }
		  },
          events: [
          {% for schedule in schedules %}
		    {
		      title: '{{ schedule.get_procedure() }}',
		      start: '{{ schedule.start_datetime }}',
		      end: '{{ schedule.end_datetime }}',
		      backgroundColor: '{{ schedule.get_color() }}',
		      url: '{{ url_for("schedules.view", schedule_id=schedule.id) }}',
		      extendedProps: {
		        schedule_id: '{{ schedule.id }}'
		      },
		    },
		    {% endfor %}
        ]});
        calendar.render();
      });

    </script>
{% endblock %}

src/templates/schedules/index.html
{% extends "base.html" %}
{% block title %}Projects{% endblock %}

{% block content %}
<div class="ui one column grid container">
    <div class="column">
	    <h1>Schedules 	
	      	<a class="ui yellow right floated button" href="{{ url_for('schedules.attribute_add') }}">Add Attribute</a>
	      	<a class="ui green right floated button" href="{{ url_for('schedules.add') }}">Add Schedule</a>
	    </h1>
	    <table class="ui striped table">
      	<thead>
	      <tr>
	      	<th>View</th>
	      	<th>Start</th>
	      	<th>End</th>
	      	<th>Complete</th>
	      	<th>Procedure</th>
	      	<th>Asigneed To</th>
	      	<th>Specimens</th>
	      	{% for attribute in attributes %}
	      		<th><a href='{{ url_for("schedules.attribute_edit", schedule_attribute_id=attribute.id) }}'>{{ attribute.name|uc_words }}</a></th>
	      	{% endfor %}
	      </tr>
	  </thead>
	  <tbody>
	      {% for schedule in schedules %}
	      <tr>
	      	<td nowrap><a href="{{ url_for('schedules.view', schedule_id=schedule.id) }}">View</a></td>
	      	<td>{{ schedule.start_datetime }}</td>
	      	<td>{{ schedule.end_datetime }}</td>
	      	<td>{% if schedule.experiments|length > 0 %}<i class="ui icon check"></i>{% endif %}</td>
	      	<td>{{ schedule.get_procedure() }}</td>
	      	<td>{{ schedule.users }}</td>
	      	<td>{{ schedule.specimens }}</td>
	      	{% for attribute in attributes %}
	      		<td>{{schedule.attributes.get(attribute.name)}}</td>
	      	{% endfor %}
	      </tr>
	      {% endfor %}
	  </tbody>
	  </table>
    </div>
</div>
{% endblock %}

src/templates/schedules/view.html
{% extends "base.html" %}
{% block title %}Schedule {{ schedule.id }}{% endblock %}

{% block content %}

<div class="ui grid container">
  <div class="column">
    <h1>Schedule {{ schedule.id }}
        <a class="ui red right floated button" href="{{ url_for('schedules.delete', schedule_id=schedule.id) }}">Delete Schedule</a>
        <a class="ui blue right floated button" href="{{ url_for('schedules.edit', schedule_id=schedule.id) }}">Edit Schedule</a>
    </h1>
    <h2>{{ schedule.get_procedure() }}</h2>
    <h4>Scheduled from {{ schedule.get_converted_datetime(schedule.start_datetime) }} to {{ schedule.get_converted_datetime(schedule.end_datetime) }}</h4>

    {% if schedule.users|length > 0 %}
      <h3>Assigned To</h3>
      {% for user in schedule.users %}
        <p>{{ user }}</p>
      {% endfor %}
    {% else %}
      <h2>No Users Assigned</h2>
    {% endif %}
    
    {% if schedule.specimens|length > 0 %}
      <h3>Specimens</h3>
      <p>{{ schedule.specimens }}</p>
    {% else %}
      <h2>No Specimens Selected</h2>
    {% endif %}

    {% if schedule.attributes|length > 0 %}
      <h3>Attributes</h3>
      {% for attribute in schedule.attributes %}
        <p>{{ attribute.name|uc_words }}: {{ schedule.attribute_values.get(attribute) }}</p>
      {% endfor %}
    {% endif %}

    {% if schedule.experiments|length == 0 %}
      <a class="ui green button" href="{{ url_for('site.collect_data', schedule_id=schedule.id) }}">Collect Data</a>
    {% else %}
      <h3>Specimen Data</h3>
      <table class="ui striped table">
        {% for experiment in schedule.experiments %}
          {% if loop.first %}
            <thead>
              <tr>
                <th>Specimen</th>
                {% for parameter in experiment.get_procedure().parameters %}
                  <th>{{ parameter.name|uc_words }}</th>
                {% endfor %}
              </tr>
            </thead>
            <tbody>
          {% endif %}
          <tr>
            <td>{{ experiment.get_specimen() }}</td>
            {% for datapoint in experiment.data_points %}
              <td>{{ datapoint.get_value() }}</td>
            {% endfor %}
          </tr>
          {% if loop.last %}
            </tbody>
          {% endif %}
        {% endfor %}
      </table>
    {% endif %}
  </div>
</div>

{% endblock %}

{% block script %}
{% if schedule.experiments|length > 0 %}
<script>
  $(document).ready(function(){
    $('table.striped.table').DataTable();
  })
</script>
{% endif %}
{% endblock %}