src/specimens/models.py
from sqlalchemy.orm.collections import attribute_mapped_collection
from sqlalchemy.ext.associationproxy import association_proxy
from src import db


class Specimens(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  name = db.Column(db.String)
  experiments = db.relationship('Experiments', backref='specimens', cascade='all, delete, delete-orphan', lazy=True)

  attribute_values = db.relationship('SpecimensValue', cascade='all, delete, delete-orphan', 
    collection_class=attribute_mapped_collection('_attribute_name'))

  attributes = association_proxy('attribute_values', 'value', 
    creator=lambda k, v: SpecimensValue(k,v))

  def __repr__(self):
    return self.name

  @classmethod
  def all(cls):
    return db.session.query(cls).all()


class SpecimensAttribute(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  name = db.Column(db.String(100), nullable=False, unique=True)

  values = db.relationship('SpecimensValue', backref="specimens_attribute", cascade='all, delete, delete-orphan')

  @classmethod
  def get_or_create(cls, name, *arg, **kw):
    with db.session.no_autoflush:
      q = cls.query.filter_by(name=name)
      obj = q.first()
      if not obj:
        obj = cls(name, *arg, **kw)
        db.session.add(obj)
    return obj


class SpecimensValue(db.Model):
  __table_args__ = (
    db.UniqueConstraint('specimens_id', 'specimens_attribute_id'),
  )
  
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  specimens_id = db.Column(db.Integer, db.ForeignKey('specimens.id'), nullable=False)
  specimens_attribute_id = db.Column(db.Integer, db.ForeignKey('specimens_attribute.id'), nullable=False)
  value = db.Column(db.String)

  # Relationship to use in association proxy
  _attribute = db.relationship('SpecimensAttribute', uselist=False, 
    foreign_keys=[specimens_attribute_id], lazy='joined')

  # Expose attribute name as proxy
  _attribute_name = association_proxy('_attribute', 'name', 
    creator=lambda v: SpecimensAttribute.get_or_create(v))

  def __repr__(self):
    return self.value

  @classmethod
  def get_by_uniq_const(cls, specimen_id, attribute_id):
    return cls.query.filter_by(specimens_id=specimen_id, specimens_attribute_id=attribute_id).first()

src/specimens/forms.py
from wtforms import form, fields, validators


class AddSpecimen(form.Form):
	name = fields.StringField('Name', validators=[validators.required()])

class EditSpecimen(AddSpecimen):
	id = fields.HiddenField()

class AddSpecimenAttribute(form.Form):
	name = fields.StringField('Name', validators=[validators.required()])
	submit = fields.SubmitField('Submit')

class EditSpecimenAttribute(AddSpecimenAttribute):
	id = fields.HiddenField()

src/specimens/controllers.py
# Import flask dependencies
import os
from flask import (
    Blueprint, request, render_template,
    redirect, url_for, jsonify)
from src import db
import src.specimens.models as SpecimensModels
import src.specimens.forms as SpecimensForms
from flask_admin import helpers
from src.helpers.decorators import check_login, check_admin


specimens = Blueprint('specimens', __name__, url_prefix='/specimens')


@specimens.route('/', methods=['GET'])
@check_login
def index():
    specimens = SpecimensModels.Specimens.query.all()
    attributes = SpecimensModels.SpecimensAttribute.query.all()
    if request.args.get('ajax'):
        data = []
        for specimen in specimens:
            data_set = []
            data_set.append(render_template('/specimens/specimen_link.html', specimen=specimen))
            for attribute in attributes:
                data_set.append(specimen.attributes.get(attribute.name))
            data.append(data_set)
        return jsonify({'data': data})
    return render_template("/specimens/index.html", specimens=specimens, attributes=attributes)


@specimens.route('/view/<int:specimen_id>', methods=['GET'])
@check_login
def view(specimen_id):
    specimen = SpecimensModels.Specimens.query.get_or_404(specimen_id)
    attributes = SpecimensModels.SpecimensAttribute.query.all()
    return render_template("/specimens/view.html", specimen=specimen, attributes=attributes)


@specimens.route('/add', methods=['GET', 'POST'])
@check_login
def add():
    attributes = SpecimensModels.SpecimensAttribute.query.all()
    form = SpecimensForms.EditSpecimen(request.form)
    if request.method == 'POST':
        specimen = SpecimensModels.Specimens()
        specimen.name = request.form.get('name')
        db.session.add(specimen)
        db.session.flush()
        for attribute in attributes:
            specimen_attribute = SpecimensModels.SpecimensValue()
            specimen_attribute.specimens_id = specimen.id
            specimen_attribute.specimens_attribute_id = attribute.id
            specimen_attribute.value = request.form.get(attribute.name)
            db.session.add(specimen_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('specimens.index'))

    return render_template("/specimens/add_or_edit.html", form=form, attributes=attributes)


@specimens.route('/edit/<int:specimen_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit(specimen_id):
    attributes = SpecimensModels.SpecimensAttribute.query.all()
    specimen = SpecimensModels.Specimens.query.get(specimen_id)
    form = SpecimensForms.EditSpecimen(request.form, obj=specimen)
    if request.method == 'POST':
        specimen.name = request.form.get('name')
        db.session.add(specimen)
        db.session.flush()
        for attribute in attributes:
            specimen_attribute = SpecimensModels.SpecimensValue.get_by_uniq_const(specimen_id, attribute.id)
            if not specimen_attribute:
                specimen_attribute = SpecimensModels.SpecimensValue()
            specimen_attribute.specimens_id = specimen.id
            specimen_attribute.specimens_attribute_id = attribute.id
            specimen_attribute.value = request.form.get(attribute.name)
            db.session.add(specimen_attribute)
            db.session.flush()
        db.session.commit()
        return redirect(url_for('specimens.index'))

    return render_template("specimens/add_or_edit.html", form=form, attributes=attributes, edit=1, specimen=specimen)


@specimens.route('/delete/<int:specimen_id>', methods=['GET'])
@check_login
@check_admin
def delete(specimen_id):
    specimen = SpecimensModels.Specimens.query.get_or_404(specimen_id)
    db.session.delete(specimen)
    db.session.commit()
    return redirect(url_for('specimens.index'))


@specimens.route('/attribute_add', methods=['GET', 'POST'])
@check_login
def attribute_add():
    form = SpecimensForms.AddSpecimenAttribute(request.form)
    if helpers.validate_form_on_submit(form):
        attribute = SpecimensModels.SpecimensAttribute()
        form.populate_obj(attribute)
        db.session.add(attribute)
        db.session.commit()
        return redirect(url_for('specimens.index'))

    return render_template("specimens/add_or_edit_attribute.html", form=form)


@specimens.route('/attribute/edit/<int:specimen_attribute_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def attribute_edit(specimen_attribute_id):
    specimen_attribute = SpecimensModels.SpecimensAttribute.query.get(specimen_attribute_id)
    form = SpecimensForms.EditSpecimenAttribute(request.form, obj=specimen_attribute)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(specimen_attribute)
        db.session.add(specimen_attribute)
        db.session.commit()
        return redirect(url_for('specimens.index'))

    return render_template("specimens/add_or_edit_attribute.html", form=form, edit=1, specimen_attribute_id=specimen_attribute_id)


@specimens.route('/attribute/delete/<int:specimen_attribute_id>', methods=['GET'])
@check_login
@check_admin
def attribute_delete(specimen_attribute_id):
    specimen_attribute = SpecimensModels.SpecimensAttribute.query.get_or_404(specimen_attribute_id)
    db.session.delete(specimen_attribute)
    db.session.commit()
    return redirect(url_for('specimens.index'))

src/templates/specimens/add_or_edit.html
{% extends "base.html" %}
{% block title %}Add Specimen{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
    <form action="{{ url_for('specimens.add') }}" method="POST" class="ui form">
        {% for f in form %}
             <div class="field">
                {% if f.name == 'id' %}
                  {{ f }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
            </div>
        {% endfor %}
        {% for attribute in attributes %}
            <div class="field">
                <label for='{{ attribute.name }}'>{{ attribute.name|uc_words }}</label>
                <input id='{{ attribute.name }}' {% if 'date' in attribute.name %} type='datetime-local' {% else %} type="text" {% endif %} name="{{ attribute.name }}" value="{{ specimen.attribute_values.get(attribute.name) }}">		
            </div>
        {% endfor %}
        <a class="ui red left floated button" href="{{ url_for('specimens.index') }}">Cancel</a>
        <button type='submit' class="ui blue right floated button">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

src/templates/specimens/add_or_edit_attribute.html
{% extends "base.html" %}
{% block title %}{% if edit %}Edit{% else %}Add{% endif %} Specimen Attribute{% endblock %}
{% block content %}

<div class="ui one column grid container">
     <div class="column">
      <h1>{% if edit %}Edit{% else %}Add{% endif %} Specimen Attribute
        {% if edit %}<a class="ui red right floated button" href="{{ url_for('specimens.attribute_delete', specimen_attribute_id=specimen_attribute_id) }}">Delete Attribute</a>{% endif %}
      </h1>
    <form action="{% if edit %}{{ url_for('specimens.attribute_edit', specimen_attribute_id=specimen_attribute_id) }}{% else %}{{ url_for('specimens.attribute_add') }}{% endif %}" method="POST" class="ui form">
        {% for f in form %}
             <div class="field">
                {% if f.name == 'submit' %}
                  <a class="ui red left floated button" href="{{ url_for('specimens.index') }}">Cancel</a>
                  {{ f(class='ui blue right floated button') }}
                {% elif f.name == 'id' %}
                  {{ f }}
                {% else %}
                  {{ f.label }}
                  {{ f }}
                {% endif %}
              </div>
        {% endfor %}
    </form>
  </div>
</div>
{% endblock %}

src/templates/specimens/index.html
{% extends "base.html" %}
{% block title %}Specimens{% endblock %}

{% block content %}
<div class="ui one column grid container">
     <div class="column">
      <h1>Specimens 
      	<a class="ui yellow right floated button" href="{{ url_for('specimens.attribute_add') }}">Add Attribute</a>
      	<a class="ui green right floated button" href="{{ url_for('specimens.add') }}">Add Specimen</a>
      </h1>

      <table class="ui striped table">
      	<thead>
	      <tr>
	      	<th>Name</th>
	      	{% for attribute in attributes %}
	      		<th><a href='{{ url_for("specimens.attribute_edit", specimen_attribute_id=attribute.id) }}'>{{ attribute.name|uc_words }}</a></th>
	      	{% endfor %}
	      </tr>
	  </thead>
	  </table>
     </div>
</div>
{% endblock %}

{% block script %}
<script>
	$(document).ready(function(){
	  $('table.striped.table').DataTable( {
          "ajax": "{{ url_for('specimens.index', ajax=1) }}"
      });
	})
</script>
{% endblock %}

src/templates/specimens/specimen_link.html
<a href="{{ url_for('specimens.view', specimen_id=specimen.id) }}">{{ specimen.name }}</a>

src/templates/specimens/view.html
{% extends "base.html" %}
{% block title %}{{ specimen.name }}{% endblock %}

{% block content %}
<div class="ui one column grid container">
    <div class="column">
	    <h1>{{ specimen.name }}
	      	<a class="ui blue right floated button" href="{{ url_for('specimens.edit', specimen_id=specimen.id) }}">Edit Specimen</a>
	      	<a class="ui red right floated button" href="{{ url_for('specimens.delete', specimen_id=specimen.id) }}">Delete Specimen</a>
	    </h1>
	    <p>{{ specimen.description }}</p>
	    {% for attribute in specimen.attributes %}
	    	<p>{{ attribute|uc_words }}: {{ specimen.attribute_values.get(attribute) }}</p>
	    {% endfor %}
    </div>
</div>
{% endblock %}